[[redirects]]
  from = "/recursos_liberados*"
  to = "/recursos-liberados"
  status = 301
  force = true
  
[[plugins]]
  package = "netlify-plugin-submit-sitemap"

  [plugins.inputs]
    baseUrl = "https://corujadigital.tech"
    sitemapPath = "/sitemap.xml"
    providers = [
      "google",
      "bing",
      "yandex"
    ]    
